64 config
XaverStiensmeier/ilarisdiscordbot pull request #66
Opened 2024-05-30 20:39 UTC by lukruh

Might be hard to see whats going on because so many files changed at once. I basically moved files around, changed import and loaded every yaml file in `config/__init__.py`. 

`text_commands.csv` -> `config/commands.yml`
`config.py` -> `config/constants.py`
`ressources/configuration.yml` -> `config/settings.yml` (this will become the main file for user configuration)

closes #64
depends on #65

2024-06-04 23:43 UTC, lukruh commented
TL;DR: 
I'm not sure if the last commit is a good solution.. It would be nice to provide an option for custom settings files. Passing them as arguments makes it really easy to run multiple instances of the bot at the same time (different tokens) or just switch between debug and production mode (differnt log settings and maybe data paths...). 
Its generally good to be able to access the settings from everywhere, but we don't want to read the yaml files several times. Right now its easy to just import what we need wherever we need it, without passing the reference around. 

1. import base libraries
2. load config files
3. import other libraries that use messages

The downside of this approach is that the (hackish) `config.load(config, args)` needs to be called before some modules are imported. This is because loading the messages depends on the settings (language) and the settings loaded could depend on arguments. If this is a problem, we could remove arguments (maybe use env variables instead) or just create a config class load data when an instance is created and pass a reference to the instance around. Which I think is more anoying, than calling the load function before other imports.

1. import everything
2. create config object
3. pass config object to every function where its needed

UPDATE:
I was too sleepy, why not just parse the arguments directly in `config/__init__.py`... I overcomplicated it for no reason. PR will be updated soon

2024-06-07 17:06 UTC, XaverStiensmeier requested changes
Check where `cfg` is still used and changes those occurrences.

2024-06-07 17:06 UTC, XaverStiensmeier commented on cogs/generalCog.py
```
  File "/home/xaver/Documents/Repos/pen_and_paper/ilaris/ilarisdiscordbot/cogs/generalCog.py", line 53, in card
    file_path = cfg.RESOURCES/"manoeverkarten"
NameError: name 'cfg' is not defined
```
must be changed everywhere.

2024-06-07 19:47 UTC, lukruh commented on cogs/generalCog.py
changed, I think this was the only one I missed(?)

2024-06-08 16:07 UTC, XaverStiensmeier approved these changes

2024-06-08 16:09 UTC, merged