75 group class
XaverStiensmeier/ilarisdiscordbot pull request #77
Opened 2024-06-09 14:10 UTC by lukruh

this is going to implement a group data model class with all the organize_groups functions as methods.. the data structure might be extended on the fly depending on discussions..
This PR will do a lot of backward incompatible changes. Please check #75 for details..

depends on #74 
closes #75
closes #80
closes #76
maybe closes #37

2024-06-17 10:43 UTC, lukruh commented
make sure created message shows correct output: https://github.com/XaverStiensmeier/ilarisdiscordbot/pull/73#pullrequestreview-2113827883

maybe also add a test case

2024-06-23 19:30 UTC, XaverStiensmeier reviewed
when listing groups a join button is shown. However, the bot's response to a group creation does not contain the join button. It should, I think.

what happens when more than one user creates a group with the same name? In that case with the new setup two roles with the same name are registered. Does this cause issues?
why does this maybe close #37 ?
why is `ERROR:root:Created category: 1254515505654403073` category creation an error log?

2024-06-23 22:03 UTC, lukruh commented
> when listing groups a join button is shown. However, the bot's response to a group creation does not contain the join button. It should, I think.

- [x] I can add the button to the created message as well.

> what happens when more than one user creates a group with the same name? In that case with the new setup two roles with the same name are registered. Does this cause issues? 

When a group is created it should check if there is one with the same (sanitized) name in the same guild, and fail if yes. I think multiple roles with the same name are allowed (should be prevented anyway). They have different ids though. And roles and categories are linked to the group by their id not the name. This way it should be possible to rename certain categories or roles without breaking the bot.
- [x] I can double check (and test) that the group creation failes for same name


> why does this maybe close #37 ? 

It gives manage permissions for the groups category channel. GMs (group owners) can create channels, assign roles etc. using discord ui (no need to use the bot). Imo we don't need the bot to manage roles like gm (see #37). If you think we do, we can keep the issue and add a gm role in the next PR.

> why is `ERROR:root:Created category: 1254515505654403073` category creation an error log?

- [x] was for debugging should be debug...

2024-06-24 08:24 UTC, XaverStiensmeier commented
If we let same name fail, we should definitely include a clear explanation why creation failed. Also, this failing should never be guild overlapping (i.e. a group in one server shouldn't prevent a group in another server)

2024-06-24 11:00 UTC, lukruh commented
Yes I forgot to add the name check in the modal form. Best practice would probably be to move the check to the class, instead of doing the same thing in tow places. I might add a Group.create() function that runs the checks and returns/raises an error or saves the group in the future.

I changed the modal response to the same message as the !gcreate command (incl join button). Before it was only a response to the user who submitted the form (not visible for anyone else), thats why it had no join button. Made it visible for everyone now.

2024-08-10 15:18 UTC, XaverStiensmeier requested changes
Some commands are not documented yet. Some errors here and there.

2024-08-10 15:18 UTC, XaverStiensmeier commented on cogs/group/organize_group.py
> +Most of the methods can probably turned into methods very simpple and makes it a lot
not really understandable

2024-08-10 15:18 UTC, XaverStiensmeier commented on ilaris_bot.py
> +            for result_str in organize_group.list_groups(sanitize(ctx.guild.name)):
I get `module 'cogs.group.organize_group' has no attribute 'list_groups'` on `!gdestroy`. Looking into organize_group it looks like you've removed the method.

2024-08-10 15:18 UTC, XaverStiensmeier commented on cogs/groupsCog.py
> +    async def reload_data(self, ctx):
reload_data       
removeallchannels 
removeallroles

need a help message

2024-08-10 15:18 UTC, XaverStiensmeier commented on cogs/groupsCog.py
>      async def gleave(
I get `argument of type 'NoneType' is not iterable` when there's no group.
The error message for when a group owner wants to leave their own group is now misleading: "This player is not part of the group." - instead they should get a message like "Can't leave your own group."

2024-08-10 15:18 UTC, XaverStiensmeier commented on cogs/groupsCog.py
> +    async def gedit(self, ctx,
`TypeError: argument of type 'NoneType' is not iterable`
when there is no group

2024-08-13 09:03 UTC, lukruh commented on ilaris_bot.py
> +            for result_str in organize_group.list_groups(sanitize(ctx.guild.name)):
This is fixed in one of the other open PR. If you have time to do the other reviews soon, I'd just wait.

2024-10-14 09:08 UTC, lukruh commented on cogs/group/organize_group.py
> +Most of the methods can probably turned into methods very simpple and makes it a lot
sorry, was more like a note to myself. To make it clear: I wanted to put the functions of this file/module into a class. Using them as a method of the class rather than individual functions allows to use the group instances instead of passing group names, server ids etc. for each function call. Since this is mostly done in this PR I think I can just remove the note.

2024-10-14 11:43 UTC, lukruh commented on cogs/groupsCog.py
> +    async def reload_data(self, ctx):
I'd change this commands in the upcomming PR #83 anyway (issue #63). I just added help messages to its checklist.

2024-10-14 12:08 UTC, lukruh commented on cogs/groupsCog.py
> +    async def gedit(self, ctx,
The user gets the general `Command execution failed: !gleave: Leave a group as a player` if the group for a given name does not exist. I think thats ok. We could try/catch it to avoid the error in the logs, or provide a more detailed error message, but in future PR there will be a dropdown to select the group from when not given correctly anyway.

2024-10-14 12:56 UTC, lukruh commented on cogs/groupsCog.py
>      async def gleave(
I think its allowed to join your own group as a player, so their might be obscure cases where owners actually "can leave their own groups". However I added another message for the (usual) case, that owner is not a player and tries to leave the group.

2024-10-14 14:32 UTC, XaverStiensmeier approved these changes

2024-10-14 17:21 UTC, merged